FROM ${NAMESPACE}/nginx-raw
MAINTAINER ${MAINTAINER}

ADD rootfs.tar /

ADD etc /etc

RUN chmod +x $(find /etc/service -name run) && ln -s /etc/service/php-fpm /service && \
    if [ ! -f /usr/bin/php ]; then ln -s /usr/bin/php5.5 /usr/bin/php; fi

EXPOSE 80 443
